-- SDKWork voice consolidated initialization baseline (sqlite)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/sqlite/0001_voice_baseline.sql
-- Consolidated legacy baseline for sdkwork-voice database module.
-- Review and replace with contract-first migrations.

-- source: crates/sdkwork-voice-generation-repository-sqlx/migrations/0001_voice_core.sql

CREATE TABLE IF NOT EXISTS voice_provider_route (
  id BIGINT PRIMARY KEY,
  route_key VARCHAR(128) NOT NULL,
  route_name VARCHAR(128) NOT NULL,
  provider_id VARCHAR(64) NOT NULL,
  client_protocol VARCHAR(64) NOT NULL,
  upstream_protocol VARCHAR(64) NOT NULL,
  upstream_config_json TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  managed_by VARCHAR(32) NOT NULL,
  notes TEXT,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_voice_provider_route_key UNIQUE (route_key)
);

CREATE TABLE IF NOT EXISTS voice_provider_route_capability (
  id BIGINT PRIMARY KEY,
  route_id BIGINT NOT NULL,
  capability VARCHAR(64) NOT NULL,
  operation_set_json TEXT NOT NULL,
  streaming BOOLEAN NOT NULL DEFAULT FALSE,
  timeout_ms BIGINT,
  request_policy_ref VARCHAR(128),
  response_policy_ref VARCHAR(128),
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_voice_route_capability UNIQUE (route_id, capability)
);

CREATE TABLE IF NOT EXISTS voice_generation_task (
  id BIGINT PRIMARY KEY,
  task_no VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL DEFAULT 0,
  organization_id BIGINT NOT NULL DEFAULT 0,
  user_id BIGINT NOT NULL DEFAULT 0,
  operation_type VARCHAR(32) NOT NULL,
  provider_code VARCHAR(64) NOT NULL,
  provider_route_id BIGINT,
  model VARCHAR(128),
  provider_task_id VARCHAR(128),
  idempotency_key VARCHAR(128),
  input_hash VARCHAR(128),
  status VARCHAR(32) NOT NULL,
  progress INTEGER NOT NULL DEFAULT 0,
  request_json TEXT NOT NULL,
  normalized_options_json TEXT,
  provider_request_json TEXT,
  provider_response_json TEXT,
  result_json TEXT,
  error_code VARCHAR(128),
  error_message TEXT,
  callback_url TEXT,
  callback_status VARCHAR(32),
  submitted_at TIMESTAMP,
  completed_at TIMESTAMP,
  expires_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_voice_generation_task_no UNIQUE (task_no),
  CONSTRAINT uk_voice_task_idempotency UNIQUE (tenant_id, operation_type, idempotency_key),
  CONSTRAINT uk_voice_task_provider_task UNIQUE (provider_code, provider_task_id)
);

CREATE TABLE IF NOT EXISTS voice_task_event (
  id BIGINT PRIMARY KEY,
  event_no VARCHAR(64) NOT NULL,
  task_id BIGINT NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  from_status VARCHAR(32),
  to_status VARCHAR(32),
  provider_code VARCHAR(64),
  provider_event_id VARCHAR(128),
  provider_task_id VARCHAR(128),
  payload_hash VARCHAR(128),
  payload_json TEXT NOT NULL,
  received_at TIMESTAMP NOT NULL,
  processed_at TIMESTAMP,
  status VARCHAR(32) NOT NULL,
  message TEXT,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_voice_task_event_no UNIQUE (event_no),
  CONSTRAINT uk_voice_task_event_provider UNIQUE (provider_code, provider_event_id)
);

CREATE TABLE IF NOT EXISTS voice_audio_artifact (
  id BIGINT PRIMARY KEY,
  artifact_no VARCHAR(64) NOT NULL,
  task_id BIGINT,
  request_id VARCHAR(64),
  kind VARCHAR(32) NOT NULL,
  artifact_type VARCHAR(32),
  title VARCHAR(256),
  voice_id VARCHAR(128),
  provider_code VARCHAR(64),
  provider_asset_id VARCHAR(128),
  artifact_index INTEGER NOT NULL DEFAULT 0,
  format VARCHAR(32),
  mime_type VARCHAR(128),
  duration_seconds INTEGER,
  checksum_json TEXT,
  transcript_text TEXT,
  translation_text TEXT,
  media_resource_json TEXT NOT NULL,
  resource_snapshot_json TEXT,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_voice_audio_artifact_no UNIQUE (artifact_no)
);

CREATE TABLE IF NOT EXISTS voice_artifact_drive_sync (
  id BIGINT PRIMARY KEY,
  sync_no VARCHAR(64) NOT NULL,
  task_id BIGINT NOT NULL,
  artifact_id BIGINT NOT NULL,
  tenant_id BIGINT NOT NULL DEFAULT 0,
  organization_id BIGINT NOT NULL DEFAULT 0,
  user_id BIGINT NOT NULL DEFAULT 0,
  anonymous_id VARCHAR(128),
  actor_type VARCHAR(32) NOT NULL,
  provider_code VARCHAR(64),
  provider_asset_id VARCHAR(128),
  artifact_index INTEGER NOT NULL DEFAULT 0,
  source_uri TEXT,
  source_hash VARCHAR(128),
  drive_space_type VARCHAR(32) NOT NULL,
  drive_space_id VARCHAR(128),
  drive_node_id VARCHAR(128),
  drive_upload_item_id VARCHAR(128),
  drive_upload_session_id VARCHAR(128),
  drive_resource_json TEXT,
  sync_status VARCHAR(32) NOT NULL,
  error_code VARCHAR(128),
  error_message TEXT,
  scheduled_at TIMESTAMP,
  uploaded_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_voice_artifact_drive_sync_no UNIQUE (sync_no),
  CONSTRAINT uk_voice_artifact_drive_sync_task_index UNIQUE (task_id, artifact_index),
  CONSTRAINT uk_voice_artifact_drive_sync_artifact UNIQUE (artifact_id)
);

CREATE TABLE IF NOT EXISTS voice_provider_webhook_event (
  id BIGINT PRIMARY KEY,
  event_no VARCHAR(64) NOT NULL,
  provider_code VARCHAR(64) NOT NULL,
  event_id VARCHAR(128) NOT NULL,
  task_id BIGINT,
  provider_task_id VARCHAR(128),
  signature_status VARCHAR(32) NOT NULL,
  payload_hash VARCHAR(128) NOT NULL,
  payload_json TEXT NOT NULL,
  processing_status VARCHAR(32) NOT NULL,
  attempt_count INTEGER NOT NULL DEFAULT 0,
  received_at TIMESTAMP NOT NULL,
  processed_at TIMESTAMP,
  error_summary TEXT,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_voice_provider_webhook_event_no UNIQUE (event_no),
  CONSTRAINT uk_voice_provider_webhook_event UNIQUE (provider_code, event_id)
);

CREATE TABLE IF NOT EXISTS voice_webhook_delivery (
  id BIGINT PRIMARY KEY,
  delivery_no VARCHAR(64) NOT NULL,
  task_id BIGINT NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  target_url TEXT NOT NULL,
  delivery_status VARCHAR(32) NOT NULL,
  attempt_count INTEGER NOT NULL DEFAULT 0,
  last_status_code INTEGER,
  last_error TEXT,
  next_retry_at TIMESTAMP,
  delivered_at TIMESTAMP,
  payload_json TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_voice_webhook_delivery_no UNIQUE (delivery_no)
);

CREATE TABLE IF NOT EXISTS voice_request_log (
  id BIGINT PRIMARY KEY,
  request_id VARCHAR(64) NOT NULL,
  trace_id VARCHAR(64) NOT NULL,
  route_id BIGINT,
  capability VARCHAR(64) NOT NULL,
  operation_id VARCHAR(128) NOT NULL,
  consumer VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  latency_ms BIGINT,
  duration_ms BIGINT,
  audio_bytes BIGINT,
  request_preview TEXT,
  response_preview TEXT,
  error_summary TEXT,
  created_at TIMESTAMP NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_voice_request_log_request_id UNIQUE (request_id)
);

CREATE INDEX IF NOT EXISTS idx_voice_provider_route_provider ON voice_provider_route (provider_id, enabled);
CREATE INDEX IF NOT EXISTS idx_voice_route_capability_route ON voice_provider_route_capability (route_id, capability);
CREATE INDEX IF NOT EXISTS idx_voice_generation_task_status ON voice_generation_task (tenant_id, operation_type, status, created_at);
CREATE INDEX IF NOT EXISTS idx_voice_generation_task_provider ON voice_generation_task (provider_code, provider_task_id);
CREATE INDEX IF NOT EXISTS idx_voice_task_event_task ON voice_task_event (task_id, created_at);
CREATE INDEX IF NOT EXISTS idx_voice_task_event_provider_task ON voice_task_event (provider_code, provider_task_id, created_at);
CREATE INDEX IF NOT EXISTS idx_voice_audio_artifact_request ON voice_audio_artifact (request_id);
CREATE INDEX IF NOT EXISTS idx_voice_audio_artifact_task ON voice_audio_artifact (task_id, status);
CREATE INDEX IF NOT EXISTS idx_voice_audio_artifact_voice ON voice_audio_artifact (voice_id, status);
CREATE INDEX IF NOT EXISTS idx_voice_artifact_drive_sync_status ON voice_artifact_drive_sync (tenant_id, sync_status, updated_at);
CREATE INDEX IF NOT EXISTS idx_voice_artifact_drive_sync_task ON voice_artifact_drive_sync (task_id, artifact_index);
CREATE INDEX IF NOT EXISTS idx_voice_artifact_drive_sync_drive_node ON voice_artifact_drive_sync (drive_space_id, drive_node_id);
CREATE INDEX IF NOT EXISTS idx_voice_provider_webhook_event_status ON voice_provider_webhook_event (provider_code, processing_status, received_at);
CREATE INDEX IF NOT EXISTS idx_voice_webhook_delivery_due ON voice_webhook_delivery (delivery_status, next_retry_at);
CREATE INDEX IF NOT EXISTS idx_voice_request_log_route_created ON voice_request_log (route_id, created_at);
CREATE INDEX IF NOT EXISTS idx_voice_request_log_capability_created ON voice_request_log (capability, created_at);
