[package]
rust-version.workspace = true
name = "sdkwork-voice-generation-repository-sqlx"
version.workspace = true
edition.workspace = true
description = "SDKWork Voice SQL storage contract and migration catalog."
license = "UNLICENSED"
publish = false


[lints]
workspace = true
[lib]
name = "sdkwork_voice_generation_repository_sqlx"
path = "src/lib.rs"

[dependencies]
async-trait.workspace = true
sdkwork-database-config = { workspace = true }
sdkwork-database-sqlx = { workspace = true }
sdkwork-utils-rust.workspace = true
sdkwork-voice-contract.workspace = true
sdkwork-voice-database-host = { workspace = true }
sdkwork-voice-service.workspace = true
sqlx.workspace = true

[dev-dependencies]
tokio.workspace = true
