[package]
rust-version.workspace = true
name = "sdkwork-voice-database-host"
edition.workspace = true
version.workspace = true
description = "SDKWork Voice database lifecycle bootstrap."


[lints]
workspace = true
[lib]
name = "sdkwork_voice_database_host"
path = "src/lib.rs"

[dependencies]
dotenvy.workspace = true
sdkwork-database-config.workspace = true
sdkwork-database-lifecycle.workspace = true
sdkwork-database-spi.workspace = true
sdkwork-database-sqlx.workspace = true
