[package]
rust-version.workspace = true
name = "sdkwork-api-voice-assembly"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-voice application HTTP plane."


[lints]
workspace = true
[lib]
name = "sdkwork_api_voice_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-web-core.workspace = true
tracing.workspace = true
sdkwork-voice-embedded-bootstrap.workspace = true
sdkwork-voice-database-host.workspace = true
sdkwork-database-sqlx.workspace = true
sdkwork-routes-voice-http-auth.workspace = true
sdkwork-routes-voice-app-api.workspace = true
sdkwork-routes-voice-backend-api.workspace = true
