[package]
rust-version.workspace = true
name = "sdkwork-voice-service"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false


[lints]
workspace = true
[lib]
name = "sdkwork_voice_service"

[dependencies]
async-trait.workspace = true
sdkwork-utils-rust.workspace = true
sdkwork-voice-contract.workspace = true
sdkwork-voice-generation-provider-spi.workspace = true
serde_json.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio.workspace = true
