[package]
rust-version.workspace = true
name = "sdkwork-voice-generation-provider-adapter"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description = "Generated SDK adapter for SDKWork speech generation."


[lints]
workspace = true
[dependencies]
async-trait.workspace = true
base64.workspace = true
cloudrouter-open-sdk.workspace = true
sdkwork-voice-generation-provider-spi.workspace = true
serde.workspace = true
serde_json.workspace = true
